name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install
      - run: pnpm test
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install
      - run: pnpm build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
