name: Test code on master branch
on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.4.0
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install
      - run: pnpm test
      - run: pnpm build
